spring:
  config:
    import: file:.env[.properties]
  profiles:
    include: jwt
  application:
    name: UACV
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PW}
  datasource:
    hikari:
      driver-class-name: ${MYSQL_DRIVER}
      jdbc-url: ${MYSQL_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PW}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq:
    host: i11c102.p.ssafy.io
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PW}

logging:
  level:
    org.hibernate.SQL: debug
#    root: debug
jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    header: Authorization
  refresh:
    header: Authorization-refresh

ffmpeg:
  path: C:\Users\SSAFY\scoop\apps\ffmpeg\current\bin\ffmpeg.exe

streaming:
  output-path: /tmp/streams
  hls:
    segment-duration: 2
    playlist-size: 3